import Head from "next/head"
import EnergyView from "src/components/energy-view"

export default function Home() {

	return (
		<>
			<Head>
				<title>SpaceX Energy Client</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/icon?family=Material+Icons"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>SpaceX Energy Client</h1>
			<EnergyView />
		</>
	)

}
