import Head from "next/head"
import Dashboard from "src/components/dashboard"
import useAuth from "src/hooks/useAuth";
import { Stack } from '@mui/system';
import { mockUser } from "src/mocks/user";
import { useState } from "react";
import LockIcon from '@mui/icons-material/Lock';
import LockOpenIcon from '@mui/icons-material/LockOpen';
import { Button, Typography } from '@mui/material';
import { mockGuest, mockAdmin } from '../src/mocks/user';
import { red } from "@mui/material/colors";

export default function Home() {
	const { login, logout } = useAuth();
	const [isAuthenticated, setIsAuthenticated] = useState(false);

	return (
		<>
			<Head>
				<title>SpaceX Energy Client</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/icon?family=Material+Icons"
				/>
				<link rel="stylesheet" href="https://unpkg.com/react-vis/dist/style.css" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Stack direction={'row'} justifyContent={'space-between'} margin={'1rem'}>
				<Typography variant='h4' sx={{ margin: '1rem 3rem 1rem 5rem' }}>SpaceX Energy Client</Typography>
				{isAuthenticated ? (<LockOpenIcon fontSize='large' onClick={() => {
					setIsAuthenticated(!isAuthenticated);
					logout
				}} />) : (<LockIcon fontSize='large' onClick={() => {
					setIsAuthenticated(!isAuthenticated);
					login(mockUser)
				}} />)}
			</Stack>
			{isAuthenticated ? (<Dashboard />) : (
				<Stack direction={'row'} justifyContent={'center'} spacing={'1rem'}>
					<Typography align='center' variant={'h5'}>Login as: </Typography>

					<Button variant='outlined' color='primary' sx={{ width: 'fit-content', }}
						onClick={() => {
							setIsAuthenticated(true);
							login(mockGuest)
						}}>Guest</Button>
					<Button variant='outlined' color='success' sx={{ width: 'fit-content' }}
						onClick={() => {
							setIsAuthenticated(true);
							login(mockAdmin)
						}}
					>Admin</Button>
					<Button variant='outlined' color='secondary' sx={{ width: 'fit-content' }}
						onClick={() => {
							setIsAuthenticated(true);
							login(mockUser)
						}}
					>User</Button>
				</Stack>
			)}
		</>
	)

}
