import Head from "next/head"
import Dashboard from "src/components/dashboard"
import useAuth from "src/hooks/useAuth";
import { Stack } from '@mui/system';
import { mockUser, mockAdmin } from "src/mocks/user";
import { useState } from "react";
import LockIcon from '@mui/icons-material/Lock';
import LockOpenIcon from '@mui/icons-material/LockOpen';

export default function Home() {
	const { login, logout } = useAuth();
	const [isAuthenticated, setIsAuthenticated] = useState(false);

	return (
		<>
			<Head>
				<title>SpaceX Energy Client</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
				/>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/icon?family=Material+Icons"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Stack direction={'row'} justifyContent={'space-between'}>
				<h1>SpaceX Energy Client</h1>
				{isAuthenticated ? (<LockOpenIcon fontSize='large' onClick={() => {
					setIsAuthenticated(!isAuthenticated);
					logout
				}} />) : (<LockIcon fontSize='large' onClick={() => {
					setIsAuthenticated(!isAuthenticated);
					login(mockUser)
				}} />)}
			</Stack>
			{isAuthenticated ? (<Dashboard />) : (<h2>Please login</h2>)}
		</>
	)

}
